sudo: false
language: node
addons:
  apt:
    packages:
    - expect

cache:
  directories:
  - node_modules
  - "$HOME/bin"

env:
  global:
  - GITHUB_EMAIL=josh@nline.io
  - GITHUB_USER=adkinsjd
  - secure: rbIShbH60M5CN9Dvu0Ex8MSAusVdynoc+8ircxayWik5/4BcxY1xxUFViGQGxfiszpAEF8LliHhqKdRbNF326A3NNICpgpw0JtyGAt8EX65rQTJ2kepsE5tBKiSAIQ7dB6szqB0+t1fru55IzGrRJAwE7uAPditaSGK8GjWyokNTwvWmjGZ0C7BKDlorZubjDQCMXwP/1THVqi0BGO89ehEVkKXwCR3JVwIeaWvt/uEBGwgCBvbXNTFK/at2fL6jmc9tbyU9KX8C2tTO6eBKYBW+8KlzVbaHIKDEscWBEoFLR3D3OT+DQ+Y4mmWwGTfByvTe4+1xUwlBD1a117CgBdTnHz8q57uZsnC+Wdqluy4kd1fnEYyXRrMDZk8fytC7yleDl56mkHGHUGtMpPPxalYpUCxkGb8Ywrf72IJeqoXEldI7VipD09H1Ple0WLXy+0V2J7RqA0X1tcLbEdTOX0q1uwkjuxW0r3HOe6u47//bUHW6pjix5rMJZEgRPAc/ZsGK95JvqJDuuZ6XAB4xGbJW6RJhRPG05lgg8bh/Dr9NAdMwDQjyXEfd5wcnEF1SYlxye2tosnWoU4wcjmq+CboLX2anuXLMV+6qQEqzVHyAQfzi4ljYEr1iC1DVNDpDMd3QINt7+k5h5J9cvvtDu403SD20KDt5Anu1aCnEGhs=

install:
- bash <( curl -sL https://particle.io/install-cli )
- export PATH="$PATH:$HOME/bin"

jobs:
  include:
  - stage: build
    env:
    - BUILD_PATH=firmware/plugwatch_F/firmware
    - MCU=PARTICLE
    - HARDWARE_VERSION=F
    - PRODUCT=7010
    - TYPE=PROD
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_F/firmware
    - MCU=PARTICLE
    - HARDWARE_VERSION=F
    - PRODUCT=7011
    - TYPE=PROD
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_F/firmware
    - MCU=PARTICLE
    - HARDWARE_VERSION=F
    - PRODUCT=8462
    - TYPE=PROD
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_F/firmware
    - MCU=PARTICLE
    - HARDWARE_VERSION=F
    - PRODUCT=8797
    - TYPE=PROD
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_F/firmware
    - MCU=PARTICLE
    - HARDWARE_VERSION=F
    - TYPE=PROD
    - PRODUCT=8379
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_F/firmware
    - MCU=PARTICLE
    - HARDWARE_VERSION=F
    - TYPE=PROD
    - PRODUCT=8605
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_F/firmware
    - MCU=PARTICLE
    - HARDWARE_VERSION=F
    - PRODUCT=9393
    - TYPE=PROD
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_I/firmware/particle
    - MCU=PARTICLE
    - HARDWARE_VERSION=I
    - PRODUCT=10935
    - TYPE=PROD
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_I/firmware/particle
    - MCU=PARTICLE
    - HARDWARE_VERSION=I
    - PRODUCT=11516
    - TYPE=STAGING
    - DRAFT=true
  - env:
    - BUILD_PATH=firmware/plugwatch_I/firmware/particle
    - MCU=PARTICLE
    - HARDWARE_VERSION=I
    - PRODUCT=11815
    - TYPE=DEV
    - DRAFT=true
  - stage: final
    env:
    - BUILD_PATH=firmware/plugwatch_I/firmware/particle
    - MCU=PARTICLE
    - HARDWARE_VERSION=I
    - PRODUCT=10804
    - TYPE=PROD
    - DRAFT=false

script:
- ./.particle-cli-login.expect "$particle_email" "$particle_password" "$(which particle)"
- "./firmware/build.py -f ${BUILD_PATH} -p ${PRODUCT} -o ${BUILD_PATH}/${MCU}_${HARDWARE_VERSION}_${PRODUCT}.bin"

before_deploy:
- git config --local user.name ${GITHUB_USER}
- git config --local user.email ${GITHUB_EMAIL}
- export BRANCHTAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "prod"; else echo
  $TRAVIS_BRANCH ; fi`
- git tag ${BRANCHTAG}-${TRAVIS_COMMIT::8}

deploy:
  - provider: releases
    api_key:
      secure: vfzXMO5+BeqxTpfc8oZez5Vqll/oXbHFBksmk1yYjsA41w/u2BM3YK+IKjsOFnTxjuwpIYNl/jagj5I6E23tF44htwiO6mmMmBwmjDDGpNf/c8RR2GnDbnAbE5yeHiv4fa/et6FdyVAHpBZdK78/XcfEM87oWXLxH6o87Db6lGAiAGxjbGcO4/t3DBKlYYaICZ31QKiGsPFGEzFGhzB9J6LC9HGUJqbVfHH5TXI5cJflxJOelrEI4DtX//Kcf4YPa2Oxou5G6gCLuw+38HLPxOSkWtzo2rygGpfXANx094ycE33JYQBZNwyXRmZOtj42VTCBGtJER/fq/xVi4+pJT5oytVfdqGecJd3zVM2N7W+sCopyD2jw8KtrxRSNG2HGtUb4IBx9on1uwePvlueE9fUoLJ7pZm07VDyzOam0rtgyy7R7eTkMIo6jo81HBRyvqA0WbXYrbEBZdZ6M5f+3V/C/finGi4ejMWk+Q8QTdGVEgcXjhk5sLvOFusOMzqUsEMBd7kZKdYyQhs5iWICdOtFZdapeX3WaLutEQeE56vAkV7+d5DViDOrsAPG3kuNAlw83follIHcFZwBZFrfW1NYCyMBz2Hy+Dv8Tul/uq/Zl5rrdXThv0Ow6U8+AtAH5XViH17fY9oXQ358bJ0BFbtwvts3OwAxFbPlxUTCXSQ0=
    file: ${BUILD_PATH}/${MCU}_${HARDWARE_VERSION}_${PRODUCT}.bin
    skip_cleanup: true
    draft: ${DRAFT}
    on:
      branch: master

  #deploy for dev and staging environments automatically
  - provider: script
    script: ./deployment-tools/deploy-firmware/deploy-firmware.py -f ${BUILD_PATH}/${MCU}_${HARDWARE_VERSION}_${PRODUCT}.bin -a $PARTICLE_API_KEY -t ${BRANCHTAG}-${TRAVIS_COMMIT::8}
    on:
      all_branches: true
      condition: ((branch =~ ^(dev-).*$) && (env(TYPE) = "DEV")) || ((branch = "staging") && (env(TYPE) = "STAGING"))
