sudo: false
language: node

addons:
  apt:
    packages:
    - expect

cache:
  directories:
  - node_modules
  - "$HOME/bin"

env:
  global:
  - GITHUB_EMAIL=josh@nline.io
  - GITHUB_USER=adkinsjd

install:
- bash <( curl -sL https://particle.io/install-cli )
- export PATH="$PATH:$HOME/bin"

jobs:
  include:
  - env: BUILD_PATH=firmware/plugwatch_F/firmware
  - env: BUILD_PATH=firmware/plugwatch_I/firmware
script:
- ./.particle-cli-login.expect "$particle_email" "$particle_password" "$(which particle)"
- particle compile electron ${BUILD_PATH} --target 0.7.0 --saveTo ${BUILD_PATH}/target.bin

before_deploy:
- git config --local user.name ${GITHUB_USER}
- git config --local user.email ${GITHUB_EMAIL}
- export BRANCHTAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "prod"; else echo
  $TRAVIS_BRANCH ; fi`
- git tag ${BRANCHTAG}-${TRAVIS_COMMIT::8}

deploy:
  provider: releases
  api_key:
    secure: j1w0dozqge7spMf4z3LMrypU31mxaDl7cUKOvL9xb9NzQhZ2x3t+P+GE75gBCP84ex1lKbtae7unFsofSy0hj8ngDgVcqjlw0HUP7kWfw3Iy0AlRiXTGHKh2I0MeHLj3XRMvuwSHeNy94AHWQXEDjuylEMbR+8ZVdYs3eyX2+AQiD1j5kIrf+RoKWdUkdaW31QvTtgWU9x7LDf6bqk/EHmss4HNOiwIGEIa0unIl45XVZIRqsO+gQ034Ci01ZEByk3d6ooNsr92yc0SKo/yIHrTutREua68m5Mqz8LW81dYKd2dJca8mJ81HJn8qkHp7zIY8jFtgUQhHxQLkHehyVKAUinR/m13nmejDV0bBJjex8S9d2yusXGPqyQ7I5FfrBQ56Joy0Me3/8SryuF+Y7GgHryiZq3Xkd7TSlLJDvKBeg+WZPn7BR4ls7JDUbRG1dP9OHCaGQpE0ZXD+XttEc7zvuxadAGAN7uusmfRqKNFzlPo32l7g9xVKa7M4qQkNMZ0tfjq5ysquT7rPyH8NIzdblHt8pF1RO9VFOopWdMV4VmSzhdjyy76LyZJyOStfXytE6iuI6iU3/0gzw/hlQiSL0C0ITtN2qFmKQIUfRI2P8UmoN7E63xppFfOeEbNVYYtsMF3AT7gozur4tWKgsvnP9bNegB9ocqsELthE6Xw=
  file: "${BUILD_PATH}/target.bin"
  on:
    repo: nline/powerwatch
