sudo: false
language: node
addons:
  apt:
    packages:
    - expect
cache:
  directories:
  - node_modules
  - "$HOME/bin"
env:
  global:
  - GITHUB_EMAIL=josh@nline.io
  - GITHUB_USER=adkinsjd
install:
- bash <( curl -sL https://particle.io/install-cli )
- export PATH="$PATH:$HOME/bin"
jobs:
  include:
  - env: BUILD_PATH=firmware/plugwatch_F/firmware
  - env: BUILD_PATH=firmware/plugwatch_I/firmware
script:
- ./.particle-cli-login.expect "$particle_email" "$particle_password" "$(which particle)"
- particle compile electron ${BUILD_PATH} --target 0.7.0 --saveTo ${BUILD_PATH}/target.bin
before_deploy:
- git config --local user.name ${GITHUB_USER}
- git config --local user.email ${GITHUB_EMAIL}
- export BRANCHTAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "prod"; else echo
  $TRAVIS_BRANCH ; fi`
- git tag ${BRANCHTAG}-${TRAVIS_COMMIT::8}
deploy:
  provider: releases
  api_key:
    secure: TcBbITwr50V42hnJXzR+HzO7Hh5p45b13opUr+i9p15luRWegQIqk12A0OG1aHnn0KRAKTOwaWQtlcNLmPrg+SxmImy9PYwSBCeZuH8eC3JrFWP5/dQhywzoeQEY1XLNmf8Ul4gqvghGiIyr1bV4NMnayEa2xh6/alQ+UQ9umM/rJy6UHHB8LkfKyJ78nZLHIiFEoUkq68DLTOehBEYiTQjkDPUdibGy1oq3zcs7Uel63ca6ieP/RFAiAmTvnbsZRAIq076Fd1B/Hhx2QvEi+pDVnXZ75QOdg5QGUW4/yHsmapW82ckmRvh6kDr77H959XDscgMaNYfWpkCv9fESgpMZ+ruAJpzUyWyAvnq0n5JDVwg+pUqKUhLGVRT30W892UadwvTF2Heq8FjzCs+A1No4acVkTOlUlVOLCPC0VuwF9ow8JQoCGQYNmqjGrCkXX79XrftYnEBkd9uQ3UurSaML/J2mx+TP5muUgNaW1bNiSouS7xuxIaEJ87wHZO1oyakX4ubNjJj0CIEEcKEKm4DmoCKwcDuUlUYP0PNdv6GTWcu0o/8LgDcLHaxv+yj5stT/AHc/ChKm0sTSoSPNjyazmZmkw/5Z5lD6OZW1FawdKZXSPluZHlIEWZtG6SjeAht5ifgmJABtAhip1o4qrhq1TlfevF7Fri081sgAMXM=
  file: "${BUILD_PATH}/target.bin"
  on:
    repo: nline/powerwatch
