#define WDI DAC
#define SD_CS A3
#define AC_N_800V_DETECT A1
#define AC_L_800V_DETECT B1
#define SERIAL_NUM B0
#define GPS_PWR_EN B2
#define SD_ENABLE C2
#define AC_PWR_EN C3
#define ACCEL_INT C4
#define SD_DETECT D6
#define PARTICLE_RST D2
#define RTC_CS C5
